// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Comment struct {
	ID       string `json:"id"`
	Content  string `json:"content"`
	Author   string `json:"author"`
	Postid   string `json:"postid"`
	Parentid string `json:"parentid"`
}

type Mutation struct {
}

type Post struct {
	ID              string `json:"id"`
	Title           string `json:"title"`
	Content         string `json:"content"`
	Author          string `json:"author"`
	CommentsEnabled bool   `json:"commentsEnabled"`
}

type Query struct {
}
